### ISSUE TITLE
Not all matches shown

### ISSUE THREAD

**Issue by MiroBabic** [sbachinin/playoffs#3]
I am going crazy here.
These data shows only match with order 0

> `{"rounds":[{"name":"Round 1"}],"matches":[{"roundIndex":0,"order":0,"sides":[{"contestantId":"65","scores":[{"mainScore":0,"isWinner":false}],"isWinner":false},{"contestantId":"56","scores":[{"mainScore":0,"isWinner":false}],"isWinner":false}]},{"roundIndex":0,"order":3,"sides":[{"contestantId":"55","scores":[{"mainScore":0,"isWinner":false}],"isWinner":false},{"contestantId":"66","scores":[{"mainScore":0,"isWinner":false}],"isWinner":false}]},{"roundIndex":0,"order":2,"sides":[{"contestantId":"57","scores":[{"mainScore":0,"isWinner":false}],"isWinner":false},{"contestantId":"67","scores":[{"mainScore":0,"isWinner":false}],"isWinner":false}]},{"roundIndex":0,"order":1,"sides":[{"contestantId":"64","scores":[{"mainScore":0,"isWinner":false}],"isWinner":false},{"contestantId":"54","scores":[{"mainScore":0,"isWinner":false}],"isWinner":false}]}],"contestants":{"65":{"players":[{"title":"Phuong Balistreri","nationality":"SK"}]},"56":{"players":[{"title":"Albert Fay","nationality":"MQ"}]},"55":{"players":[{"title":"Lonnie Beier","nationality":"IL"}]},"66":{"players":[{"title":"Arthur Volkman","nationality":"TK"}]},"57":{"players":[{"title":"Allie Cronin","nationality":"FK"}]},"67":{"players":[{"title":"Marci Streich","nationality":"KY"}]},"64":{"players":[{"title":"Adolph Senger","nationality":"FK"}]},"54":{"players":[{"title":"Brandy Mills","nationality":"MO"}]}}}`

and these shows correct all matches
`

> {"rounds":[{"name":"Round 1"},{"name":"Round 2"},{"name":"Round 3"}],"matches":[{"roundIndex":0,"order":1,"sides":[{"contestantId":"7","scores":[{"mainScore":44,"isWinner":true}],"isWinner":true},{"contestantId":"8","scores":[{"mainScore":12,"isWinner":false}],"isWinner":false}]},{"roundIndex":0,"order":2,"sides":[{"contestantId":"6","scores":[{"mainScore":45,"isWinner":false}],"isWinner":false},{"contestantId":"9","scores":[{"mainScore":77,"isWinner":true}],"isWinner":true}]},{"roundIndex":0,"order":3,"sides":[{"contestantId":"5","scores":[{"mainScore":34,"isWinner":true}],"isWinner":true},{"contestantId":"10","scores":[{"mainScore":11,"isWinner":false}],"isWinner":false}]},{"roundIndex":1,"order":0,"sides":[{"contestantId":"4","scores":[{"mainScore":33,"isWinner":true}],"isWinner":true},{"contestantId":"7","scores":[{"mainScore":11,"isWinner":false}],"isWinner":false}]},{"roundIndex":1,"order":1,"sides":[{"contestantId":"9","scores":[{"mainScore":44,"isWinner":false}],"isWinner":false},{"contestantId":"5","scores":[{"mainScore":55,"isWinner":true}],"isWinner":true}]},{"roundIndex":0,"order":0,"sides":[{"contestantId":"4","scores":[{"mainScore":25,"isWinner":true},{"mainScore":23,"isWinner":true}],"isWinner":true},{"contestantId":"11","scores":[{"mainScore":25,"isWinner":false},{"mainScore":12,"isWinner":false}],"isWinner":false}]},{"roundIndex":2,"order":0,"sides":[{"contestantId":"4","scores":[{"mainScore":45,"isWinner":true}],"isWinner":true},{"contestantId":"5","scores":[{"mainScore":32,"isWinner":false}],"isWinner":false}]},{"roundIndex":2,"order":1,"sides":[{"contestantId":"7","scores":[{"mainScore":44,"isWinner":true}],"isWinner":true},{"contestantId":"9","scores":[{"mainScore":12,"isWinner":false}],"isWinner":false}]}],"contestants":{"7":{"players":[{"title":"Briana Frami","nationality":"LK"}]},"8":{"players":[{"title":"Ian Hegmann","nationality":"ZM"}]},"6":{"players":[{"title":"Yong Abernathy","nationality":"AT"}]},"9":{"players":[{"title":"Timothy Bartoletti","nationality":"CA"}]},"5":{"players":[{"title":"Vern Kreiger","nationality":"SZ"}]},"10":{"players":[{"title":"Anisha Abernathy","nationality":"PR"}]},"4":{"players":[{"title":"Alan Bode","nationality":"CZ"}]},"11":{"players":[{"title":"Ali Gibson","nationality":"JE"}]}}}

`

I dont see any error in console, data are generated on backend by same function and visually it looks ok to me, but plenty of games do not show all matches and rounds.

Any clue why, or what to check?

**Comment by sbachinin** [comment]
Just a quick guess for now,
Try adding
```
        {
            "name": "Round 2"
        },
        {
            "name": "Round 3"
        }
```
to the first data.

It needs an appropriate number of objects in the `rounds` array, otherwise it can't construct a proper tree

**Comment by MiroBabic** [comment]
Thanks, I thought that rounds should be actual value how many are present. When I calculated how many rounds total should be, it works fine. Thanks

**Comment by sbachinin** [comment]
Thanks for raising the issue.
Developer experience definitely needs improvement in such cases.
