### ISSUE TITLE
Any way to suppress the winner's tick?

### ISSUE THREAD

**Issue by peterlondon1** [sbachinin/playoffs#8]
I'd like **not** to show a tick for the winner, but still to retain the bold text for the winner and grey text for the loser.

Is there a way of replacing the tick with an empty string?

thanks.

**Comment by sbachinin** [comment]
I think now it's possible only with css:
```
.bracket-root .side-info-item.winner-mark {
      display: none;
}
```

**Comment by peterlondon1** [comment]
That's great, thanks. 
Is it possible to display a different character instead?

**Comment by sbachinin** [comment]
Currently the checkmark is hardcoded.
With css you can do some tricks though. 

```
.bracket-root .default-winner-svg {
      display: none !important;
}
.bracket-root .side-info-item.winner-mark::before {
    content: "\2605"
}
```

`content` can be only text. In this example it's a single unicode character

**Comment by peterlondon1** [comment]
Perfect, thanks so much! I'm nearly done so I hope I don't need to bother you much more! I really appreciate your help.

**Comment by peterlondon1** [comment]
Solution provided, thanks.
